In [6]:
import numpy as np

In [7]:
x=np.array(([3,5],[5,1],[10,2]), dtype=float )
y=np.array(([75],[82],[93]) ,dtype=float )


In [8]:
#scaling data
X=x/np.amax(x,axis=0)
Y=y/100

In [48]:
class Neural_Network(object):
    def  __init__(self):
        #defining hyperparameters
        self.inputlayersize=2
        self.outputlayersize=1
        self.hiddenlayersize=3
        
        #weights (number = 2 because the network is a three layered network)
        
        self.w1=np.random.randn(self.inputlayersize, self.hiddenlayersize)
        self.w2=np.random.randn(self.hiddenlayersize, self.outputlayersize)
    def forward(self,x):
        #forward propagation
         self.z2 = np.dot(x,self.w1)
         self.a2=self.sigmoid(self.z2)
         self.z3=np.dot(self.a2,self.w2)
         predy=self.sigmoid(self.z3)
         return predy
        
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
    
    def sigmoidprime(self,z):
        return np.exp(-z)/((1+np.exp(-z))**2)
        
    def costFunctionPrime(self,X,Y):
    #computing the derivative of the cost function
        self.predy=self.forward(X)
        delta3=np.multiply(-(Y-self.predy),self.sigmoidprime(self.z3))
        djdw2=np.dot(self.a2.T,delta3)
        
        delta2=np.dot(delta3,self.w2.T)*(self.sigmoidprime(self.z2))
        djdw1=np.dot(X.T,delta2)
        return djdw1,djdw2
        
    
    
        
        
        

In [49]:
NN = Neural_Network()
predy=NN.forward(x)

In [50]:
predy

array([[0.88362698],
       [0.88777827],
       [0.88927564]])

In [51]:
Y

array([[0.75],
       [0.82],
       [0.93]])

In [52]:
cost1=NN.costFunctionPrime(X,Y)

In [57]:
djdw1 , djdw2 = NN.costFunctionPrime(X,Y)

In [58]:
djdw1

array([[-0.00063943, -0.00058897, -0.00063325],
       [ 0.00091121,  0.00280964,  0.00091138]])

In [59]:
djdw2

array([[ 0.00104963],
       [-0.00017195],
       [ 0.0014094 ]])

In [ ]:
scalar =2
NN.w1=NN.w1-scalar*djdw1
NN.w2=NN.w2-scalar*djdw2